#!/bin/bash
# Unbound Concepts full public website backup version 1.3

# This script simply calls the mysql and sitefiles backup scripts, then 
#+ tarballs the entire result and scp's it over to the vpn for safe-keeping
#
# @author Benjamin Bengfort
# @created 2011-01-24 09:50:00 -400
# @version 1.3

#
# Set executable paths:
# 
MYSQL_BAK="/usr/local/bin/mysqlbackup"
FILES_BAK="/usr/local/bin/sitefilesbackup"
SCP=$(which scp) 
DATE=$(which date)
TAR=$(which tar)

#
# Set important paths:
#
USER_DIR="$HOME"
BAK_DIR="sitebackup/"
REMOTE_DIR="benjamin@vpn.unboundconcepts.com:./server.bak/"
REMOTE_PORT=22

#
# Codes
#
ROOT_UID=0
E_NOTROOT=87

# Ensure root user is doing the backup
if [ "$UID" -ne "$ROOT_UID" ]; then 
    echo "Backup may require root permissions, please use sudo"
    exit $E_NOTROOT
fi 

# A function that pads a string to center it.
# Param 1 is the word or string to center (default blank string)
# Param 2 is the length of the final string (default length of param 1)
# Param 3 is the character to use as padding (default ' ')
center() {
    if [ "$1" ]; then
        word="$1";
    else
        word="";
    fi;

    if [ "$2" ]; then
        len=$(($2));
    else
        len=${#word};
    fi;

    if [ "$3" ]; then
        padding="$3";
    else
        padding=" ";
    fi;

    while [ ${#word} -lt $len ]; do
        word="$word$padding";
        if [ ${#word} -lt $len ]; then
            word="$padding$word"
        fi;
    done;
    echo "$word";
}

# A function that prints out the banner text.
banner()
{
    BTEXT="Full Backup on $(hostname)"
    echo -e $(center '' 50 +)
    echo -e "|$(center "$BTEXT" 48)|"
    echo -e $(center '' 50 +)    
}

# Just to be smart, a main function rather than just putting this in at the top level
main()
{
    # Print out banner
    banner

    echo -e "This program will do the folling tasks:"
    echo -e "    1. Back up MySQL, you may need user name and password"
    echo -e "    2. Back up the site files"
    echo -e "    3. Back up the Apache configuration"
    echo -e "    4. Wrap it all up and send to the VPN"

    # Do MySQL Backup
    $MYSQL_BAK
    # Do Files Backup
    $FILES_BAK
    # Tar the result into a single thing 
    echo -e "Backup complete, now zipping things up to send to the VPN"
    CREATED=$($DATE +%F)
    cd $USER_DIR
    FNAME="$HOME/$(hostname)-$CREATED-backup.tar.bz2"
    $TAR -jvcf $FNAME $BAK_DIR
    #Send it to remote storage:
    $SCP -P $REMOTE_PORT $FNAME $REMOTE_DIR
    # Cleanup 
    rm $FNAME
}


main
